{% set name = "palpy" %}
{% set version = "1.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d42d537bc4af2b0d88af1bb2fa19d6911d78df72de0f94ce6a371a8c6535c540

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - numpy
    - setuptools
    - setuptools-scm
    - cython
  run:
    - python

test:
  imports:
    - palpy

about:
  home: https://github.com/Starlink/palpy
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'Python interface to the PAL positional astronomy library'

extra:
  recipe-maintainers:
    - timj
    - beckermr
