{% set name = "palpy" %}
{% set version = "1.8.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 64eda4042b03deb1153cac804b4f7fba19b0d2b3f8ffaeadf10fc51869d5e9d2

build:
  number: 5
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: True  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cython
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - palpy

about:
  home: https://github.com/Starlink/palpy
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'Python interface to the PAL positional astronomy library'

extra:
  recipe-maintainers:
    - beckermr
