{% set name = "palpy" %}
{% set version = "1.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d60bbae67ec16155dc3a09e9f209240b478ad724f627b8c0ceb3c01d0d58fd0f

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython <3                              # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - numpy
    - cython <3
  run:
    - python
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - palpy

about:
  home: https://github.com/Starlink/palpy
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: 'Python interface to the PAL positional astronomy library'

extra:
  recipe-maintainers:
    - beckermr
